version: '3.9'
services:
  mongo:
    image: mongo:5.0.8
    container_name: mongodb
    restart: always
    environment:
      TZ: "Asia/Tehran"
    ports:
      - "27017"
    volumes:
      - database:/data/db

  redis:
    image: redis:6.2-alpine
    container_name: redis
    restart: always
    environment:
      TZ: "Asia/Tehran"
    ports:
      - "6379"

  api:
    build: .
    container_name: api
    ports:
      - "5000:5000"
    restart: always
    depends_on:
      - mongo
      - redis
    volumes:
      - node_uploads:/usr/src/app/public/uploads/

volumes:
  database: { }
  node_uploads: { }